### PR TITLE
Re: Pull request #28

### PR DESCRIPTION
**Pull request by stefsmeets**
Not sure how this works, but let's see ;-)

I made some small adjustments to your changes

### CODE REVIEW

**Comment by asdfdsa** [comment]
Thanks for the changes!

I don't quite agree with the commit "revert cosine change", since cos(x + 90) should equal -sin(x), which means there should be a negative sign before np.sin(). Do you agree with it?

**Comment by stefsmeets** [comment]
Totally agree, but it's not the same as np.sin(), which is what it was changed from:
https://github.com/stefsmeets/instamatic/pull/28/files#diff-2db33445c3d2eb2b0ae8ac28f956aec0L24

**Comment by stefsmeets** [comment]
I did change it a while ago to make it more in line with other software. The definition now better matches with RED and such:
https://github.com/stefsmeets/instamatic/commit/45f970ce8762948624e80fc7ad525fdbe213f4d4#diff-2db33445c3d2eb2b0ae8ac28f956aec0L25

Maybe it does not match the numbers anymore that you are using, but you can update it in the config by putting a `-` in front.

**Comment by asdfdsa** [comment]
Yeah I figured, you also reverted the sign on rotation_axis at the same commit. Then I agree. Thanks!

**Pull request merged**
